### ISSUE TITLE
Is there a timeline for when this will be available on marketplace?

### ISSUE THREAD

**Issue by skullgoblet1089** [looker-open-source/extension-gen-ai#17]
Hello! My company has an enterprise Looker license. We are very eager to experiment with advanced analytics experiences with looker using gen ai. Is there an ETA for when the extension will be on the marketplace? Is the code stable enough for us to use it to host our own extension?

**Comment by Baatof** [comment]
Hello 

I try to implement the extension in our platform but the display is very very very slow...
The extension is loading to infinity ...

I follow all the things mentioned in the ReadMe.

**Comment by kaue** [comment]
@skullgoblet1089 thanks for showing interest in using this extension! currently we dont have any ETA when this will be available in the marketplace. But it's on the roadmap, when we have more information we will share here.
