### ISSUE TITLE
Syntax issue with main.tf

### ISSUE THREAD

**Issue by LaniusSenatorShrike** [looker-open-source/extension-gen-ai#19]
Hi Team, 

I found a potential bug in `main.tf` terraform file. Here is the [line in main.tf](https://github.com/looker-open-source/extension-gen-ai/blob/main/deployment/terraform/main.tf#L144) which is missing a closing curly bracket. I tried to raise PR but I've got Authentication failure error. Please check and fix if it's legit or guide/enable me to do so. I'm trying to deploy this repo to the Looker instance we use. 

here is figure denoting the error while trying `terraform init`

![Screenshot 2024-02-08 at 14 04 29](https://github.com/looker-open-source/extension-gen-ai/assets/132745849/c5ec1b4c-8af8-4231-9f64-ffe3174e38ae)

Best

**Comment by ricardolui** [comment]
Fixed. Thanks for raising this issue.
