### ISSUE TITLE
Running infinitly

### ISSUE THREAD

**Issue by Baatof** [looker-open-source/extension-gen-ai#21]
Hello

I try to implement the extension in our platform but the display is very very very slow...
The extension is loading to infinity ...

I follow all the things mentioned in the ReadMe.

**Comment by J-Day** [comment]
I have the same problem. On clicking "Generate", get infinite loading and no results back

**Comment by kaue** [comment]
Dear @J-Day and @Baatof,

We kindly request your assistance in checking for errors in the Cloud console. Specifically, we would like you to:

1. Navigate to the BigQuery interface.
2. Check the project history section for any errors.
3. If no errors are found, open the dev tools console and share any error logs displayed there.

**Comment by ricardolui** [comment]
Hi 
@J-Day , 
Have you check the permissions and the console logs? Usually it's due to configuration.
We'll try to track error messages for these.
