### ISSUE TITLE
TF Jobs don't use region var, so functions created in US rather than specified region

### ISSUE THREAD

**Issue by benthompsonhx** [looker-open-source/extension-gen-ai#23]
The three resources:

- create_bq_model_llm
- insert_default_settings
- create_bq_remote_udf

do not specify a region. So when passing in EU as bq_region this is ignored, and they above are run in the US. The other infrastructure does not live in the US so you get an error: 'Not found: Connection bqllm'

This is corrected by passing in:

```
resource "google_bigquery_job" "create_bq_model_llm" {
  job_id = "create_looker_llm_model-${formatdate("YYYYMMDDhhmmss", timestamp())}"
  location = var.bq_region
  ...
}
````

**Comment by ricardolui** [comment]
Thanks, will try to test this out with this modification.

**Comment by ricardolui** [comment]
Hi @benthompsonhx , I've already deployed a new version of the terraform and tested using eu region, it works.
Let me know if there is anything else.
